name: even_better
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  http: ^0.13.4
  image_picker:
  video_player: ^2.2.5
  animated_theme_switcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

flutter:

  assets:
    - assets/images/

  fonts:
    - family: Billabong
      fonts:
        - asset: assets/fonts/Billabong.ttf
    - family: Windsong
      fonts:
        - asset: assets/fonts/Windsong.ttf
    - family: Festive
      fonts:
        - asset: assets/fonts/Festive-Regular.ttf
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
          weight: 400
        - asset: assets/fonts/DancingScript-Medium.ttf
          weight: 500
        - asset: assets/fonts/DancingScript-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/DancingScript-Bold.ttf
          weight: 700
    - family: EB
      fonts:
        - asset: assets/fonts/EBGaramond-ExtraBold.ttf
    - family: EBI
      fonts:
        - asset: assets/fonts/EBGaramond-BoldItalic.ttf

  uses-material-design: true
